### ISSUE TITLE
fetch_mldata Deprecated and Down Routinely

### ISSUE THREAD

**Issue by ZaydH** [t-sakai-kure/pywsl#12]
I was looking at your nnPU `chainer` implementation.  If I am not mistaken, it seems to download data from mldata.org.  This `sklearn` [issue report](https://github.com/scikit-learn/scikit-learn/issues/8588) discusses the instability of mldata.org and how it often goes down for extended periods of time.  For example, mldata.org is down at the moment.

When you run the `fetch_mldata` command, you get the warning in `sklearn`:

> DeprecationWarning: Function fetch_mldata is deprecated; fetch_mldata was deprecated in version 0.20 and will be removed in version 0.22

What are your thoughts on moving away from `fetch_mldata` to an alternative?  Different alternatives include:

* Hosting the file on Github (probably in a different repository)
* Moving to another source for the data, e.g., `torchvision`

I would be happy to work with you on this if you are interested.

**Comment by ZaydH** [comment]
@kiyoshiiriemon makes a good proposed changed in nnPU's repository.  The change he proposes in his [issue report](https://github.com/kiryor/nnPUlearning/issues/6) seems to be very clean and straightforward.

**Comment by t-sakai-kure** [comment]
Thank you for your comment, @ZaydH.
The function fetch_openml looks nice as long as people use sklearn v0.21.2>.
I will update the code in a few days.

**Comment by ZaydH** [comment]
@t-sakai-kure Tomoya you're right.  

It may be worth adding a `requirements.txt` to the package to make it more portable and robust going forward since dependencies may obsolete commands.

**Comment by t-sakai-kure** [comment]
@ZaydH Zayd, thanks.
I changed the code based on this comment https://github.com/scikit-learn/scikit-learn/issues/12504#issuecomment-435631425.
