### ISSUE TITLE
Problem in installation

### ISSUE THREAD

**Issue by shehrozskhan** [t-sakai-kure/pywsl#13]
Hi, 
When I try to install using pip, I am getting the following error
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-dwrj5xhj/pywsl/

Could you please check if installation is working properly?

**Comment by t-sakai-kure** [comment]
Hi, 

Thank you for your report.
Maybe, an easy solution would be to update setuptools, i.e., 
`pip install -U setuptools`

I will resolve the issue soon.

**Comment by t-sakai-kure** [comment]
Now, pip works. Thank you for your waiting.
