### ISSUE TITLE
Feature Request: Use PNU classification with a scikit-learn cross validator

### ISSUE THREAD

**Issue by Y-oHr-N** [t-sakai-kure/pywsl#6]
Hello.

Currently, ``PNU_SL`` function internally computes the cross validation score. I'd like to use PNU classification with a scikit-learn cross validator. Is it possible to implement ``PNU_SL`` class conforming to scikit-learn?

Thank you.

**Comment by t-sakai-kure** [comment]
Hi @Y-oHr-N, 

I modified `PNU_SL` so that it is compatible with scikit-learn classifier. 
The previous `PNU_SL` was changed to `PNU_SL_FastCV`. 

Please try `demo_pnu_mr_cv.py` and `demo_pnu_mr_illust.py` in examples/ssl.

**Comment by Y-oHr-N** [comment]
Thank you for refinement!
